name: virtual_try_on
description: AI-powered virtual try-on mobile app built with Flutter, Provider, MVC, and Firebase.
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  provider: ^6.1.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
