name: virtual_try_on
description: A Flutter + Firebase virtual try-on app using Provider and MVC.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  logger: ^2.3.0
  dio: ^5.5.0+1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.2
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # Image/Editing utils (crop placeholder)
  extended_image: ^9.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
